Repository JosiasPires/login-page, pull requests merged in 2022-11, with the labels that each got.

#3 docs: add basic templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: documentation, enhancement

#4 ci: add basic workflows to pipeline
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: enhancement

#6 docs: add license type and readme doc
  LICENSE
  README.md
Labels: documentation, enhancement

#8 feat: format new structure root
  public/background.jpg
  public/index.html
  public/style.css
Labels: enhancement

#10 feat: add docker configs
  .dockerignore
  .env.example
  .gitignore
  Dockerfile
  docker-compose.yml
  nginx.conf
Labels: enhancement

#16 feat: add auth post fetch api
  public/index.js
Labels: enhancement

#18 Merge "develop" into "main"
  .dockerignore
  .env.example
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .gitignore
  Dockerfile
  LICENSE
  README.md
  docker-compose.yml
  nginx.conf
  public/background.jpg
  public/index.html
  public/index.js
  public/style.css
Labels: enhancement

#20 Bugfix/root pages
  .editorconfig
  assets/background.jpg
  assets/script.js
  assets/style.css
  index.html
  main.js
  package.json
  public/index.html
Labels: bug, enhancement
